### ISSUE TITLE
jsoftload package does not exist

### ISSUE THREAD

**Issue by ghost** [TheThirdOne/JSoftFloat#5]
I'm trying to install RARS assembler to an offline machine. I get jsoftload package does not exist when I run build-jar.sh. So I extracted jsoftload source to my machine bu I still get this error.

**Comment by TheThirdOne** [comment]
You are getting the error because the JSoftFloat submodule is not updated in your clone.

While inside the rars directory executing `git submodule update` will clone JSoftFloat and check it out appropriately. Alternatively when cloning adding the `--recusive` flag (`git clone https://github.com/TheThirdOne/rars --recursive`) will initialize any submodules.

This is mentioned in the thethirdone/rars#57, but there definitely should be some documentation in the README.md or an error message from build.sh that indicates how to solve the error.

**Comment by TheThirdOne** [comment]
I made an issue in RARS for lack of documentation. I do not consider this an issue of JSoftFloat because JSoftFloat doesn't have a strict build system or dependencies of any kind.
